# This rule is not used by the project services-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to oso.opea.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: services-operator
    app.kubernetes.io/managed-by: kustomize
  name: serviceoperator-viewer-role
rules:
- apiGroups:
  - oso.opea.io
  resources:
  - serviceoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oso.opea.io
  resources:
  - serviceoperators/status
  verbs:
  - get
